lint:
  files_exist:
    - conf/igenomes.config
    - conf/test_full.config
    - conf/test.config
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/download_pipeline.yml
    - .github/workflows/nf-test.yml
    - .gitignore
    - conf/modules.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - docs/README.md
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/download_pipeline.yml
    - conf/modules.config
    - conf/igenomes_ignored.config
  modules_config: false
  multiqc_config: false
  nextflow_config: false
  modules_lint: false
  subworkflows_lint: false
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Yasset Perez-Riverol, Joshua Beale
  description: nf-core pipeline for crosslinking mass spectrometry analysis using xiSEARCH
  force: false
  is_nfcore: false
  name: relink
  org: bigbio
  outdir: .
  version: 1.0.0dev
