name: xifdr
description: Run xiFDR for false discovery rate correction on crosslinking search results
keywords:
  - proteomics
  - crosslinking
  - mass spectrometry
  - FDR
  - xiFDR
tools:
  - xifdr:
      description: |
        xiFDR is a tool for FDR (False Discovery Rate) estimation and filtering
        of crosslinked peptide identifications from xiSEARCH results.
      homepage: https://www.rappsilberlab.org/software/xifdr/
      documentation: https://github.com/Rappsilber-Laboratory/xiFDR
      licence: ["Apache-2.0"]
input:
  - crosslink_results:
      type: file
      description: CSV files with crosslinking search results from xiSEARCH (collected from all samples)
      pattern: "*.csv"
  - fasta:
      type: file
      description: FASTA database file used in the search
      pattern: "*.{fasta,fa}"
  - config:
      type: file
      description: xiSEARCH configuration file used for the crosslinking search
      pattern: "*.conf"
  - link_fdr:
      type: integer
      description: Link-level FDR threshold (percentage)
output:
  - results:
      type: file
      description: FDR-corrected results in CSV format
      pattern: "fdr_*.csv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@ypriverol"
  - "@jbeale2023"
maintainers:
  - "@ypriverol"
