name: mass_recalibration
description: Calculate mass error from linear search results and recalibrate MGF files
keywords:
  - proteomics
  - mass spectrometry
  - recalibration
  - mass error
  - MGF
tools:
  - pyopenms:
      description: |
        pyOpenMS is a Python wrapper for the OpenMS library, providing
        functionality for mass spectrometry data processing.
      homepage: https://pyopenms.readthedocs.io/
      documentation: https://pyopenms.readthedocs.io/
      licence: ["BSD-3-Clause"]
  - polars:
      description: |
        Polars is a lightning-fast DataFrame library for Rust and Python.
      homepage: https://pola.rs/
      documentation: https://docs.pola.rs/
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample1' ]
  - linear_results:
      type: file
      description: CSV file with linear search results from xiSEARCH
      pattern: "*.csv"
  - peaks_file:
      type: file
      description: TSV file with peak annotations from xiSEARCH linear search
      pattern: "*.peaks.tsv"
  - mgf_file:
      type: file
      description: Original MGF file to be recalibrated
      pattern: "*.mgf"
  - do_plotting:
      type: boolean
      description: Whether to generate mass error plots
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - mgf:
      type: file
      description: Recalibrated MGF file
      pattern: "recal_*.mgf"
  - error_report:
      type: file
      description: CSV file with calculated mass errors
      pattern: "mass_error_*.csv"
  - plots:
      type: file
      description: Mass error distribution plots (optional)
      pattern: "*.png"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@ypriverol"
  - "@jbeale2023"
maintainers:
  - "@ypriverol"
